##############################################
# FILE GENERATED AUTOMATICALLY FROM TERRAFORM
# THIS FILE SHOULD NOT BE EDITED BY HAND
##############################################

name: eslint-reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      HUSKY_SKIP_HOOKS: 1
      HUSKY: 0
    steps:
      - uses: actions/checkout@v3.5.0
      - name: eslint
        uses: reviewdog/action-eslint@v1.18.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
