##############################################
# FILE GENERATED AUTOMATICALLY FROM TERRAFORM
# THIS FILE SHOULD NOT BE EDITED BY HAND
##############################################

name: Build and Deploy

on: master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Setup node âš™ï¸
        uses: actions/setup-node@v2
      - name: Install âš™ï¸ï¸
        run: npm ci
      - name: Build ğŸ”§
        run: npm run build
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: "."
